drinks/urls.py
from django.urls import path
from drinks.views import *
app_name='drinks'
urlpatterns = [
    path('Epm/',Epm,name='Epm'),
    path('oldmonk/',oldmonk,name='oldmonk'),
]

food/urls.py
from django.urls import path
from food.views import *
app_name='food'
urlpatterns = [
    path('biryani/',biryani,name='biryani'),
    path('dbc/',dbc,name='dbc'),
]

project14/urls.py
from django.contrib import admin
from django.urls import path,include
import food,drinks
urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('drinks/',include('drinks.urls')),
]

drinks/models.py
from django.db import models

# Create your models here.

food/models.py
from django.db import models

# Create your models here.

drinks/views.py
from django.shortcuts import render

# Create your views here.
def Epm(request):
    return render(request,'Epm.html')
def oldmonk(request):
    return render(request,'oldmonk.html')

food/views.py
from django.shortcuts import render

# Create your views here.
def biryani(request):
    return render(request,'biryani.html')
def dbc(request):
    return render(request,'dbc.html')

templates/Epm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>8pm is famous in Utter Pradesh</h1>


        <a href="{% url 'food:biryani'%}"><h1>Go to biryani</h1></a>
        <a href="{% url 'food:dbc'%}"><h1>Go to dbc</h1></a>
        <a href="{% url 'drinks:oldmonk'%}"><h1>Go to oldmonk</h1></a>
        
    </center>
</body>
</html>

templates/biryani.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Biryani is one of the famous dish in hydrabad</h1>

        <a href="{% url 'food:dbc'%}"><h1>Go to dbc</h1></a>
        <a href="{% url 'drinks:Epm'%}"><h1>Go to 8pm</h1></a>
        <a href="{% url 'drinks:oldmonk'%}"><h1>Go to oldmonk</h1></a>
        
    </center>
</body>
</html>

templates/dbc.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
    <h1>Dal Bhat Chokha is one of the famous dish Bihar</h1>

        <a href="{% url 'food:biryani'%}"><h1>Go to biryani</h1></a>
        <a href="{% url 'drinks:Epm'%}"><h1>Go to 8pm</h1></a>
        <a href="{% url 'drinks:oldmonk'%}"><h1>Go to oldmonk</h1></a>
    </center>
</body>
</html>

templates/oldmonk.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        
    <h1>Oldmonk Is good for cold</h1>


        <a href="{% url 'food:biryani'%}"><h1>Go to biryani</h1></a>
        <a href="{% url 'food:dbc'%}"><h1>Go to dbc</h1></a>
        <a href="{% url 'drinks:Epm'%}"><h1>Go to 8pm</h1></a>
        
    </center>
</body>
</html>